[build]
  command = "npm install && npm run build"
  publish = "dist"  # Cambiado de 'build' a 'dist' que es el directorio por defecto de Vite
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"